var config = {
    mapBoxToken: 'pk.eyJ1IjoibGlicmFyaWVzaGFja2VkIiwiYSI6IlctaDdxSm8ifQ.bxf1OpyYLiriHsZN33TD2A',
    mapTilesDark: 'https://api.mapbox.com/styles/v1/mapbox/dark-v9/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibGlicmFyaWVzaGFja2VkIiwiYSI6IlctaDdxSm8ifQ.bxf1OpyYLiriHsZN33TD2A',
    mapTilesLight: 'https://api.mapbox.com/styles/v1/mapbox/light-v9/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibGlicmFyaWVzaGFja2VkIiwiYSI6IlctaDdxSm8ifQ.bxf1OpyYLiriHsZN33TD2A',
    mapTilesStreets: 'https://api.mapbox.com/styles/v1/mapbox/streets-v9/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibGlicmFyaWVzaGFja2VkIiwiYSI6IlctaDdxSm8ifQ.bxf1OpyYLiriHsZN33TD2A',
    mapAttribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors.  Contains OS data &copy; Crown copyright and database right 2016.  Contains Royal Mail data &copy; Royal Mail copyright and Database right 2016.  Contains National Statistics data &copy; Crown copyright and database right 2016.',
    bngcrs: '+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs',
    data: [
        //{ name: 'Survey of Reef Habitat around Eddystone Reef, Plymouth', category: 'Biodiversity', type: 'wms', url: 'http://213.122.160.75/scripts/mapserv.exe?map=D:/Websites/MESHAtlantic/map/MESHAtlanticWMS.map' },
        //{ name: 'St John\'s Lake intertidal biotope map (Tamar estuary, Plymouth)', category: 'Biodiversity', type: 'wms', url: 'http://213.122.160.75/scripts/mapserv.exe?map=D:/Websites/MESHAtlantic/map/MESHAtlanticWMS.map' },
        { name: 'Ancient Trees', category: 'Trees', type: 'geoJson', url: '/data/ancient-trees.geojson' },
        { name: 'Green Space', category: 'Green space', type: 'geoJson', url: '/data/green-space-2016.geojson' },
        //{ name: 'Local Nature Reserves', category: 'Green space', type: 'geoJson', url: '/data/localnaturereserves.geojson' },
        { name: 'Libraries', category: 'Education and Culture', type: 'geoJson', url: '/data/pcclibraries.geojson' },
        { name: 'Neighbourhoods', category: 'Place', type: 'geoJson', url: '/data/pccneighbourhoods.geojson' },
        { name: 'Ownership', category: 'Place', type: 'geoJson', url: '/data/pccownership.geojson' },
        { name: 'Play Spaces', category: 'Play', type: 'geoJson', url: '/data/play-spaces.geojson' },
        { name: 'Bus stop locations', category: 'Green travel', type: 'geoJson', url: '/data/plymouthbusstoplocations.geojson' },
        { name: 'Plymouth Pear', category: 'Trees', type: 'geoJson', url: '/data/plymouth-pear.geojson' },
        { name: 'Plymouth Schools', category: 'Education and Culture', type: 'geoJson', url: '/data/plymouthschools.geojson' },
        { name: 'Public Rights of Way', category: 'Green travel', type: 'geoJson', url: '/data/prow.geojson' },
        //{ name: 'Slipways', category: 'Green travel', type: 'csv', url: '/data/public-slipways.csv' },
        { name: 'South West Coast Path Route', category: 'Green travel', type: 'geoJson', url: '/data/swcproute.geojson' },
        { name: 'Listed Buildings', category: 'Heritage', type: 'geoJson', url: '/data/listdedbuildings.geojson' },
    ]
};